server:
  port: 5555

spring:
  application:
    name: gateway

eureka:
  instance:
    instance-id: gateway-5555
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/  # 注册中心访问地址
zuul:
  sensitive-headers: # 全局忽略敏感头，即允许接收 cookie 等请求头信息
  routes:
    javaj: # 任意名字，保证唯一即可
      path: /javaj/** # 自定义，真正用到的请求地址
      service-id: api  # 路由到的目标服务名称
  ignored-patterns:
  - /api/user/**
  prefix: /open