server:
  port: 8100

spring:
  application:
    name: USER

eureka:
  instance:
    instance-id: user-api-8100
    prefer-ip-address: true # 访问路径可以显示 IP
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/  # 注册中心访问地址