provider:
  # 名称
  name: provider
  # 版本
  version: 1.0
  # 版权年份
  copyrightYear: 2019
  # 文件上传路径
  profile: profile/
  # 获取ip地址开关
  addressEnabled: true
server:
  port: 80

spring:
  application:
    name: api

eureka:
  client:
#    register-with-eureka: false # 不向注册中心注册自己
    fetch-registry: true        # 是否检索服务
    service-url:
      defaultZone: http://localhost:9000/eureka/  # 注册中心访问地址

feign:
  client:
    config:
      default:
        connect-timeout: 10000
        read-timeout: 20000
      service-test:
        connect-timeout: 10000
        read-timeout: 20000