server:
  port: 10000

spring:
  application:
    name: CONFIG
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Uncle-LiuY/config.git
          username: nanfonjin@foxmail.com
          password: ly838061522
eureka:
  instance:
    instance-id: config-api
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/  服务注册中心ַ