server:
  port: 10000

spring:
  application:
    name: CONFIG
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
    config:
      server:
        git:
          uri: https://github.com/Uncle-LiuY/config.git
          username: nanfonjin@foxmail.com
          password: 888888
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: 123456
management:
  endpoints:
    web:
      exposure:
        include: '*' # 暴露接口
eureka:
  instance:
    instance-id: config-api
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/  # 注册中心访问地址